### ISSUE TITLE
No dashboards loading due to issue with Google Visualisation

### ISSUE THREAD

**Issue by sammcewan** [keen/dashboards#72]
Apologies, I don't have time to look further but all our dashboards and all your example ones are down for the same reason.

Seen here and easy to find in the JS console:
http://keen.github.io/dashboards/examples/starter-kit/

Really hope you can get a fix up soon, big day for us and we were hoping to have the dashboards up on our displays.

**Comment by dustinlarimer** [comment]
Hey, @sammcewan - thanks for pointing this out! I haven't tracked down the exact issue, but the problem seems to be isolated to versions of our JS lib prior to v3.1.0 (this dashboard repo uses v3.0.7).

Would you mind testing this out on your end, to make sure I'm not totally crazy:
https://d26b395fwzu5fz.cloudfront.net/3.1.0/keen.js

**Comment by sammcewan** [comment]
Works great!

**Comment by dustinlarimer** [comment]
@sammcewan awesome, I'll get the repo updated.

I'm going to bump this to the latest (v3.2.1) which includes a few minor breaking changes but lots of enhancements and performance improvements. If any of these changes affect you, just stick w/ v3.1.0. Sound good?

Release notes: https://github.com/keen/keen-js/releases/tag/v3.2.0
